### ISSUE TITLE
下载仿真器, 抱歉，您无法访问此项目，因为它违反了我们的服务条款。

### ISSUE THREAD

**Issue by ovjust** [HPCL-EI/RoboWaiter#5]
![image](https://github.com/HPCL-EI/RoboWaiter/assets/12697538/62be5406-33a2-49c0-b988-00c18ecaca54)

**Comment by Caiyishuai** [comment]
链接已更新：https://drive.google.com/file/d/1ayAQZbPOyQV2W-V_ZdYv6AoqLOg0zvm1/view?usp=sharing

如果还打不开，看看百度网盘：
链接：https://pan.baidu.com/s/1WvyYcnTTsSNNFHGCCvryCw 
提取码：1wft 
--来自百度网盘超级会员V7的分享

**Comment by ovjust** [comment]
感谢
